[package]
name = "tinytext"
version = "0.1.0"
edition = "2021"
description = "A tiny plaintext editor"
license = "MIT"
publish = false

[dependencies]
glib-unix = "0.22.8"
gtk = { version = "0.11.5", package = "gtk4", features = ["v4_14"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"
